name: Feature integration
description: File a bug report
title: "[Integration]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        - [ ] Development
        - [ ] Release
        - [ ] Tag
        - [ ] Main
